-- =============================================================================
-- Migration: seed_project_sections
-- Fecha:     2026-09-26
-- =============================================================================
-- Carga las secciones de detalle de chaquies y neweken. GENERADO desde
-- src/i18n/strings.ts, para que el copy sea idéntico al de las páginas que
-- este template reemplaza.
--
-- Los títulos que estaban partidos en titleA/highlight/titleB se recomponen
-- en una sola frase con el fragmento resaltado [entre corchetes].
-- =============================================================================

-- chaquies
insert into public.project_sections (project_id, kind, position, data)
select p.id, v.kind, v.position, v.data
from public.projects p
cross join (values
  ('hero', 0, '{"images":[{"src":"/projects/chaquies/newHero.jpg","alt":"Chaquíes — vineyards & mountains"},{"src":"/projects/chaquies/sum-exterior.jpg","alt":"SUM exterior"},{"src":"/projects/chaquies/kids-zone.jpg","alt":"Kids zone"},{"src":"/projects/chaquies/piscina-cubierta.jpg","alt":"Indoor heated pool"}],"ctaHref":"#amenities","ctaLabel":{"es":"Ver amenities","en":"See amenities"},"showDescription":true}'::jsonb),
  ('specs', 1, '{"extra":[{"label":{"es":"Distancia a la plaza","en":"Distance to the square"},"value":{"es":"300 m","en":"300 m"}}]}'::jsonb),
  ('what_is', 2, '{"title":{"es":"Más de [20.000 m²] de desarrollo en el corazón de Cafayate.","en":"Over [20,000 m²] of development in the heart of Cafayate."},"body":{"es":["Chaquíes integra 164 unidades de monoambientes, 1 y 2 dormitorios con un masterplan de 13 amenities pensados para vivir, descansar y rentabilizar.","A 300 metros de la plaza principal, conjuga ubicación privilegiada, escala arquitectónica y un programa de servicios que define un nuevo estándar para Cafayate."],"en":["Chaquíes brings together 164 units of studios, 1 and 2-bedroom apartments with a masterplan of 13 amenities designed to live, rest and earn.","300 meters from the main square, it combines a privileged location, architectural scale and a program of services that sets a new standard for Cafayate."]},"metrics":[{"value":"164","label":{"es":"unidades","en":"units"}},{"value":"+20.000","label":{"es":"m² desarrollados","en":"m² developed"}},{"value":"13","label":{"es":"amenities","en":"amenities"}}],"image":"/projects/chaquies/sum-exterior.jpg"}'::jsonb),
  ('context', 3, '{"eyebrow":{"es":"El contexto","en":"The context"},"title":{"es":"¿Por qué invertir hoy en [Cafayate]?","en":"Why invest in [Cafayate] today?"},"subtitle":{"es":"Una de las plazas turísticas que más crece en el norte argentino — ubicación, escasez de oferta premium y demanda sostenida.","en":"One of the fastest-growing tourist destinations in northern Argentina — location, scarce premium supply and sustained demand."},"reasons":[{"eyebrow":{"es":"Destino turístico consolidado","en":"Established tourist destination"},"title":{"es":"Vino, montañas y patrimonio","en":"Wine, mountains and heritage"},"body":{"es":"Cafayate combina paisaje de altura, bodegas reconocidas y un casco histórico vivo. Un destino que crece año tras año en ocupación y derrame turístico.","en":"Cafayate combines high-altitude landscape, renowned wineries and a living historic center. A destination that grows year after year in occupancy and tourism spillover."}},{"eyebrow":{"es":"Demanda de alojamiento permanente","en":"Permanent demand for accommodation"},"title":{"es":"Turismo + segunda residencia","en":"Tourism + second home"},"body":{"es":"Una plaza donde la oferta de departamentos premium aún es escasa frente a una demanda creciente — alquiler temporario, fines de semana largos y temporada alta.","en":"A market where the supply of premium apartments is still scarce against a growing demand — short-term rentals, long weekends and high season."}},{"eyebrow":{"es":"Ubicación estratégica","en":"Strategic location"},"title":{"es":"300 metros de la plaza principal","en":"300 meters from the main square"},"body":{"es":"El corazón de Cafayate: caminás a bodegas, restaurantes y la vida del pueblo. Una ubicación que no se repite y define el valor en el tiempo.","en":"The heart of Cafayate: walk to wineries, restaurants and town life. A location that doesn''t repeat itself and defines value over time."}}]}'::jsonb),
  ('amenities', 4, '{}'::jsonb),
  ('pull_quote', 5, '{"quote":{"es":"Una ubicación a metros de la plaza, una arquitectura pensada para el descanso y un programa de amenities que [redefine el estándar de Cafayate].","en":"A location meters from the square, an architecture designed for rest and a program of amenities that [redefines the Cafayate standard]."}}'::jsonb),
  ('gallery', 6, '{"eyebrow":{"es":"Renders del proyecto","en":"Project renders"},"title":{"es":"El proyecto en imágenes.","en":"The project in images."},"images":[{"src":"/projects/chaquies/fachada.jpg","label":{"es":"Fachada · vista frontal","en":"Facade · front view"},"wide":true},{"src":"/projects/chaquies/sum-interior.jpg","label":{"es":"SUM · interior","en":"SUM · interior"}},{"src":"/projects/chaquies/piscina-cubierta.jpg","label":{"es":"Piscina interior climatizada","en":"Indoor heated pool"}},{"src":"/projects/chaquies/obra-avance.jpg","label":{"es":"Avance de obra","en":"Construction progress"},"wide":true}]}'::jsonb),
  ('cta', 7, '{"eyebrow":{"es":"Invertí en pozo","en":"Pre-construction investment"},"lead":{"es":"Anticipo","en":"Down payment"},"amount":40,"amountSuffix":"%","trail":{"es":" + 24 cuotas","en":" + 24 installments"},"body":{"es":"Una estructura de financiación pensada para inversores que buscan capturar el valor de Cafayate antes de la entrega.","en":"A financing structure designed for investors looking to capture Cafayate''s value before delivery."},"cards":[{"title":{"es":"Plantas","en":"Floor plans"},"body":{"es":"Solicitalas por mail →","en":"Request them by email →"},"href":"#contacto"},{"title":{"es":"Brochure","en":"Brochure"},"body":{"es":"Material completo del proyecto →","en":"Full project material →"},"href":"#contacto"},{"title":{"es":"Amenities","en":"Amenities"},"body":{"es":"Ver los 13 amenities →","en":"See all 13 amenities →"},"href":"#amenities"}]}'::jsonb)
) as v(kind, position, data)
where p.slug = 'chaquies';

-- neweken
insert into public.project_sections (project_id, kind, position, data)
select p.id, v.kind, v.position, v.data
from public.projects p
cross join (values
  ('hero', 0, '{"images":[{"src":"/projects/neweken/hero.png","alt":"Neweken entrance"},{"src":"/projects/neweken/aerial-2.jpg","alt":"Panoramic view"},{"src":"/projects/neweken/aerial-1.jpg","alt":"Aerial view"},{"src":"/projects/neweken/construction.jpg","alt":"Construction progress"}],"ctaHref":"#avance-de-obra","ctaLabel":{"es":"Ver avance de obra","en":"See construction progress"},"showDescription":false}'::jsonb),
  ('specs', 1, '{"extra":[{"label":{"es":"Inversión desde","en":"Investment from"},"value":{"es":"USD 45.900","en":"USD 45,900"}}]}'::jsonb),
  ('what_is', 2, '{"eyebrow":{"es":"¿Qué es Neweken?","en":"What is Neweken?"},"title":{"es":"Un proyecto pensado para transformar el [crecimiento energético] en renta inmobiliaria real.","en":"A project designed to turn [energy growth] into real-estate income."},"body":{"es":["Vaca Muerta es una matriz productiva en expansión, con demanda habitacional estructural y sostenida en el tiempo. En ese contexto Neweken: un proyecto inmobiliario pensado para transformar ese crecimiento en renta inmobiliaria real.","Más de 100 departamentos totalmente equipados, contratos con empresas petroleras multinacionales y un modelo de gestión 100% administrado por NEOS. Vos invertís en un activo productivo, NEOS gestiona, vos percibís la renta."],"en":["Vaca Muerta is an expanding productive engine with structural and sustained housing demand. In that context: Neweken, a real-estate project designed to turn that growth into real income.","More than 100 fully equipped apartments, contracts with multinational oil companies and a management model 100% run by NEOS. You invest in a productive asset, NEOS manages, you collect the income."]},"metrics":[{"value":"+100","label":{"es":"departamentos equipados","en":"fully equipped apartments"}},{"value":"100%","label":{"es":"gestionado por NEOS","en":"managed by NEOS"}},{"value":"1er mes","label":{"es":"comenzás a percibir renta","en":"you start earning rent"}}],"image":"/projects/neweken/aerial-1.jpg"}'::jsonb),
  ('context', 3, '{"eyebrow":{"es":"El contexto","en":"The context"},"title":{"es":"¿Por qué invertir hoy en [Vaca Muerta]?","en":"Why invest in [Vaca Muerta]today?"},"subtitle":{"es":"El principal motor de crecimiento económico de la Argentina en la próxima década — y una de las oportunidades inmobiliarias más sólidas del mercado actual.","en":"Argentina''s main engine of economic growth for the next decade — and one of the strongest real-estate opportunities in today''s market."},"reasons":[{"eyebrow":{"es":"Oportunidad de escala global","en":"Global-scale opportunity"},"title":{"es":"Inversiones extranjeras comprometidas","en":"Committed foreign investment"},"body":{"es":"Vaca Muerta proyecta exportaciones por más de USD 50.000 millones a 2030 — capital, estabilidad y continuidad operativa garantizadas por las principales energéticas del mundo.","en":"Vaca Muerta projects exports of over USD 50 billion by 2030 — capital, stability and operational continuity backed by the world''s leading energy companies."}},{"eyebrow":{"es":"Demanda habitacional permanente","en":"Permanent housing demand"},"title":{"es":"Perfiles técnicos y profesionales","en":"Technical and professional profiles"},"body":{"es":"El crecimiento sostenido de la actividad energética implica una demanda habitacional estructural de perfiles técnicos y operativos, con proyecciones de empleo crecientes entre 2025 y 2030.","en":"Sustained growth in energy activity drives a structural housing demand from technical and operational workers, with rising employment projections between 2025 and 2030."}},{"eyebrow":{"es":"Crecimiento demográfico acelerado","en":"Accelerated population growth"},"title":{"es":"Añelo: de 7.000 a 30.000 habitantes","en":"Añelo: from 7,000 to 30,000 inhabitants"},"body":{"es":"Centro operativo de Vaca Muerta. La presión habitacional genera condiciones ideales para inversiones rentables, alta ocupación y valorización constante del capital.","en":"Vaca Muerta''s operational center. Housing pressure creates ideal conditions for profitable investment, high occupancy and steady capital appreciation."}}]}'::jsonb),
  ('pull_quote', 4, '{"eyebrow":{"es":"El momento es ahora","en":"The moment is now"},"quote":{"es":"La infraestructura energética avanza más rápido que el desarrollo urbano. Quienes invierten hoy lo hacen [antes de que la brecha entre oferta y demanda se cierre], capturando los mayores márgenes de rentabilidad.","en":"Energy infrastructure is advancing faster than urban development. Those who invest today do so [before the gap between supply and demand closes], capturing the highest profit margins."}}'::jsonb),
  ('masterplan', 5, '{"eyebrow":{"es":"Master plan","en":"Master plan"},"title":{"es":"6 etapas. [4 entregadas, 2 en obra.]","en":"6 stages. [4 delivered, 2 under construction.]"},"image":"/projects/neweken/render.jpg","stages":[{"name":"Etapa 1","status":{"es":"Finalizada y en funcionamiento","en":"Finished and operating"},"active":false},{"name":"Etapa 2","status":{"es":"Finalizada y en funcionamiento","en":"Finished and operating"},"active":false},{"name":"Etapa 3","status":{"es":"Finalizada y en funcionamiento","en":"Finished and operating"},"active":false},{"name":"Etapa 4","status":{"es":"Finalizada y en funcionamiento","en":"Finished and operating"},"active":false},{"name":"Etapa 5","status":{"es":"En obra","en":"Under construction"},"active":true},{"name":"Etapa 6","status":{"es":"En obra","en":"Under construction"},"active":true}]}'::jsonb),
  ('gallery', 6, '{"eyebrow":{"es":"Avance de obra","en":"Construction progress"},"title":{"es":"El proyecto en imágenes.","en":"The project in images."},"images":[{"src":"/projects/neweken/aerial-2.jpg","label":{"es":"Vista panorámica del complejo","en":"Panoramic view of the complex"}},{"src":"/projects/neweken/construction.jpg","label":{"es":"Avance constructivo","en":"Construction progress"}},{"src":"/projects/neweken/aerial-1.jpg","label":{"es":"Vista cenital del master plan","en":"Top view of the master plan"},"wide":true}]}'::jsonb),
  ('cta', 7, '{"eyebrow":{"es":"Inversión","en":"Investment"},"lead":{"es":"Desde","en":"From"},"amountPrefix":"USD ","amount":45900,"body":{"es":"Accedé a Vaca Muerta con un ticket bajo y una estructura pensada para inversores que buscan rentabilidad, previsibilidad y gestión profesional.","en":"Access Vaca Muerta with a low ticket and a structure designed for investors looking for returns, predictability and professional management."},"cards":[{"icon":"blueprint","title":{"es":"Plantas","en":"Floor plans"},"body":{"es":"Solicitalas por mail →","en":"Request them by email →"},"href":"#contacto"},{"icon":"document","title":{"es":"Brochure","en":"Brochure"},"body":{"es":"Material completo del proyecto →","en":"Full project material →"},"href":"#contacto"},{"icon":"play","title":{"es":"Avance de obra","en":"Construction progress"},"body":{"es":"Master plan + galería →","en":"Master plan + gallery →"},"href":"#avance-de-obra"}]}'::jsonb)
) as v(kind, position, data)
where p.slug = 'neweken';

